//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivityTrackerEntities : DbContext
    {
        public ActivityTrackerEntities()
            : base("name=ActivityTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessCategory> ProcessCategories { get; set; }
        public virtual DbSet<ProcessWindow> ProcessWindows { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
