//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessWindow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessWindow()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int processWindowTitleID { get; set; }
        public string processWindowTitle { get; set; }
        public Nullable<int> processCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ProcessCategory ProcessCategory { get; set; }
    }
}
